### ISSUE TITLE
VLC playlist

### ISSUE THREAD

**Issue by Wallkerock** [mustafaozhan/Arc-Maia-Grey-Theme#3]
![screenshot from 2018-03-07 17-55-59](https://user-images.githubusercontent.com/29909846/37106038-04ff028a-2231-11e8-91a2-98f691d9310f.png)

**Comment by mustafaozhan** [comment]
Hello,

i checked the picture now and it seems it is not related with theme, it seems that it is related with icon theme can you check and let me know please ?

**Comment by Wallkerock** [comment]
Hi,
if you switch to Arc Maia Grey (light theme), icon size is OK, but in Arc Maia Grey Dark the icons are huge. It is the same icons theme and I think, the problem is probably in theme. I was trying other icons, but the problem still exist.

**Comment by mustafaozhan** [comment]
It is interesting because i do not have this issue and i can not check my changes also.

**Comment by Wallkerock** [comment]
I tested this theme on the Arch Linux with Gnome. But now i tried this theme on my laptop with Manjaro Gnome, and I have this problem again. Maybe you are using another linux distribution with another version of the Gnome (or DE) and VLC. My VLC version is 3.0.1-2. Gnome 3.26.2. Or maybe the problem is only my. I think, next people can give the answer where is problem. (sry for english)

**Comment by mustafaozhan** [comment]
I am testing also on Arch Linux and desktop environment is XFCE. So i just wonder this problem occurs also with other Icon themes right ? I mean problem is with Arc Maia Grey Dark + Your Icon theme or Arc Maia Grey Dark + All icon themes ?

**Comment by Wallkerock** [comment]
Yes, all icons themes. Now I deleted VLC configs in my /home/USER/ and start VLC new, but still the same problem. Later, when I come back to home, I will try this theme on second OS, on second disk. But I mean, it will be the same. Can you ask other people about this problem? If this problem is only my, I apologize for your lost time.

**Comment by mustafaozhan** [comment]
No no thank you for your feedback. It is good to have some issues to fix :) Actually figure out one more problem while we were trying to solve this :)

**Comment by ghost** [comment]
Can confirm this. Only affects Arc-Maia-Grey-Dark. Others are OK. [Screenshot here.](https://drive.google.com/open?id=1_zb7NLVD0rYc2beCfMAMpq1Wf8HmrICb)

**Comment by mustafaozhan** [comment]
Sorry to announce that it will not be fixed. PRs welcome
