### ISSUE TITLE
install script is so ghetto

### ISSUE THREAD

**Issue by coleifer** [mustafaozhan/Arc-Maia-Grey-Theme#5]
It uses sudo and blows away the git checkout...bad juju man. You should be checking that the uid of the user running the script is root and if not prompt for sudo. Or even better, install into $HOME/.themes if not root.

And don't blow away the git repo after copying. That's so weird.

**Comment by mustafaozhan** [comment]
Hey hello.

You are right ! But i just make that script to auto update my theme. And I am not expert either 😄 So if you want to contribute Pull Requests are welcomed. Maybe than I will lokk your script and change my other repos also.
